NO_ISSUE Added neo4j dependencies
FridaysForFoodies/Tender-Backend pull request #2
Opened 2020-12-08 18:05 UTC by m-oehme

2020-12-10 15:45 UTC, Kaes3kuch3n requested changes
Ein paar kleine Anmerkungen hätte ich noch :P

2020-12-10 15:45 UTC, Kaes3kuch3n commented on docker-compose.yml
> +    image: library/neo4j:latest
Ist zwar jetzt für unser Projekt wahrscheinlich nicht so wichtig, aber allgemein sollte lieber ne bestimmte Version festgelegt werden.
```suggestion
    image: neo4j:4.2
```

2020-12-10 15:45 UTC, Kaes3kuch3n commented on docker-compose.yml
> +      - db-data:/data/db
```suggestion
      - db-data:/data
```
Der Pfad `/data/db` passt nur bei MongoDB 😅 Neo4j hat n bisschen mehr Stuff in /data

2020-12-10 15:45 UTC, Kaes3kuch3n commented on docker-compose.yml
> +      - "7474:7474"
```suggestion
      - "7474:7474"
    environment:
      - NEO4J_AUTH=${DATABASE_USERNAME}/${DATABASE_PASSWORD}
```
Damit Docker auch die entsprechenden Daten aus der .env lädt

2020-12-10 15:45 UTC, Kaes3kuch3n commented on src/server.ts
> +  const driver = neo4j.driver(
Ich glaube, da fehlt noch ein driver.close() am Ende der server.ts :)

2020-12-11 13:14 UTC, m-oehme commented on src/server.ts
> +  const driver = neo4j.driver(
Soweit ich weis muss man das für den driver nicht machen. Nur für die jeweiligen Sessions (also im Resolver/Provider)

2020-12-11 13:30 UTC, Kaes3kuch3n commented on src/server.ts
> +  const driver = neo4j.driver(
Alles klar 👍 Kenne mich mit Neo4j noch nicht wirklich aus, kenne das nur von anderen Datenbanken 😅

2020-12-11 13:30 UTC, Kaes3kuch3n approved these changes

2020-12-11 13:30 UTC, merged